#!/bin/bash

brightness_file="/sys/class/backlight/intel_backlight/brightness"
brightness=$(cat $brightness_file)

max_brightness_file="/sys/class/backlight/intel_backlight/max_brightness"
max_brightness=$(cat $max_brightness_file)
delta=1250

sum=$(($brightness+$delta))

if [ $max_brightness -gt $sum ]; then
	echo $sum > "/sys/class/backlight/intel_backlight/brightness"
fi
