#!/bin/bash

FIFO="$HOME/.config/mwww/commands.fifo"

case "$1" in
  hide)
    echo "hide" > "$FIFO"
    ;;
  show)
    echo "show" > "$FIFO"
    ;;
  reload-style)
    echo "reload-style" > "$FIFO"
    ;;
  reload-config)
    echo "reload-config" > "$FIFO"
    ;;
  context)
    if [ -z "$2" ]; then
      echo "Error: Missing value for 'context' command."
      echo "Usage: $0 context ['local', 'spotify']"
      exit 1
    fi
    echo "context:$2" > "$FIFO"
    ;;
  *)
	  echo "Usage: mwww { hide | show | reload-style | reload-config | context ['local', 'spotify'] }"
    exit 1
    ;;
esac

