#!/bin/bash

SCRIPT_DIR=$(dirname "$(readlink -f "$0")")
SOCK="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"

dummy_window_class="mwww-dummy-unfocus"
mwww_daemon_title="mwww-daemon"

dummy_window_pid=""
dummy_window_address=""
current_workspace=$(hyprctl activeworkspace -j | jq '.id')

get_window_titles_on_workspace() {
    hyprctl -j clients | jq -r ".[] | select(.workspace.id == $1) | .title"
}

spawn_dummy() {
    if [[ -n "$dummy_window_pid" ]]; then
	return 1
    fi

    $SCRIPT_DIR/wayland-client/client &

    pid=$!
    dummy_window_pid=$pid
}

kill_dummy() {
    if [[ -n "$dummy_window_pid" ]]; then
        kill "$dummy_window_pid" 2>/dev/null
        dummy_window_pid=""
    fi
}

only_mwww_daemon_on_workspace() {
    workspace="$1"
    window_titles=($(get_window_titles_on_workspace "$workspace"))

    # no windows at all → return false
    if [[ ${#window_titles[@]} -eq 0 ]]; then
        return 1
    fi

    # only mwww-daemon → return true
    if [[ ${#window_titles[@]} -eq 1 && "${window_titles[0]}" == $mwww_daemon_title ]]; then
        return 0
    fi

    return 1
}

socat - UNIX-CONNECT:"$SOCK" | while read -r line; do
    case "$line" in
	# workspace change
	workspace\>*)
	    new_workspace="${line#workspace>>}"

            kill_dummy

            if only_mwww_daemon_on_workspace "$new_workspace"; then
                spawn_dummy
            fi

            current_workspace="$new_workspace"
            ;;
	# window close
	closewindow\>*)
	    closed_window_address="${line#closewindow>>}"

	    # after a window is closed check whether mwww-daemon is the only window left in the workspace
	    # and if so spawn the dummy window
	    if [[ $closed_window_address != $dummy_window_address ]] && only_mwww_daemon_on_workspace "$current_workspace"; then
		spawn_dummy
	    fi
	    ;;
	# window open
	openwindow\>*)
	    opened_window="${line#openwindow>>}"

	    if [[ $opened_window == *"$dummy_window_class"* ]]; then
		is_dummy=true
	    else
		is_dummy=false
	    fi

	    if [[ "$is_dummy" == true ]]; then
		dummy_window_address=$(hyprctl -j clients | jq -r ".[] | select(.class == \"$dummy_window_class\") | .address")
		# strip the address from 0xabc123 to just abc123
		# needed to match format of 'closed_window_address' from closewindow event
		dummy_window_address=${dummy_window_address#0x}
	    fi

	    # if opened window is not the dummy window itself nor mwww-daemon
	    # then close our dummy window
	    if [[ "$is_dummy" == false && $opened_window != *"$mwww_daemon_title"* ]]; then
	        kill_dummy
	    fi
	    ;;
	# layer open
	openlayer\>*)
	    opened_layer="${line#openlayer>>}"
	    
	    # kill dummy window as soon as wofi is opened
	    # this way by the time an app is launched there will be no dummy window
	    # 
	    # without this logic, the dummy window would be closed only a moment after
	    # the app is launched, thus the app's launch behavior would get affected
	    if [[ $opened_layer == "wofi" ]]; then
	        kill_dummy
	    fi
	    ;;
	# layer close
	closelayer\>*)
	    closed_layer="${line#closelayer>>}"

	    # spawn dummy window in case we close wofi without launching a window
	    if [[ $closed_layer == "wofi" ]] && only_mwww_daemon_on_workspace "$current_workspace"; then
		spawn_dummy
	    fi
	    ;;
    esac
done

