#!/bin/bash


# Get the theme name
THEME="$1"
if [ -z "$THEME" ]; then
    echo "Usage: set-theme '<theme>'"
    exit 1
fi


# Check if theme dir exists
THEME_DIR="$HOME/.config/themes/$THEME"
if [ ! -d "$THEME_DIR" ]; then
    echo "Theme dir $THEME does not exist"
    exit 1
fi


# Check if all required theme files exist
REQUIRED_FILES=(
    "/hypr/hyprland.conf"
    "/hypr/hyprlock/avatar"
    "/hypr/hyprlock.conf"
    "/kitty/current-theme.conf"
    "/kitty/kitty.conf"
    "/mwww/config.yaml"
    "/mwww/style.css"
    "/waybar/style.css"
    "/wofi/style.css"
    "/starship.toml"
    "/theme-picker/config.yaml"
    "/cava/config"
    "/wallpaper"
)

for file in "${REQUIRED_FILES[@]}"; do
    if [ ! -f "$THEME_DIR$file" ]; then
        echo "Missing required file: $THEME_DIR$file"
        exit 1
    fi
done


# Copy all theme files to corresponding files in ~/.config
CONFIG_DIR="$HOME/.config"

swww img "$THEME_DIR/wallpaper" --transition-fps 60 --transition-step 255 --transition-duration 1.5 --transition-type wipe &

# sleep for swww to run smoothly
# otherwise swww may lag, probably because other part of the script is CPU-bound and interferes with swww animation render
# first, we wait for swww img process to finish (which exits as soon as it sends the command to the daemon)
# then, we also sleep for duration equal to {swww --transition-duration} + small delta to be sure the new wallpaper is fully rendered

swww_pid=$!
wait $swww_pid
sleep 1.75


cp "$THEME_DIR/wallpaper" "$CONFIG_DIR/wallpapers/current"
echo "wallpaper changed"


cp "$THEME_DIR/hypr/hyprland.conf" "$CONFIG_DIR/hypr/hyprland.conf"
echo "hyprland conf applied"


cp "$THEME_DIR/kitty/current-theme.conf" "$CONFIG_DIR/kitty/current-theme.conf"
cp "$THEME_DIR/kitty/kitty.conf" "$CONFIG_DIR/kitty/kitty.conf"
kill -SIGUSR1 $(pgrep kitty)
echo "kitty conf applied"


cp "$THEME_DIR/mwww/config.yaml" "$CONFIG_DIR/mwww/config.yaml"
cp "$THEME_DIR/mwww/style.css" "$CONFIG_DIR/mwww/style.css"
mwww reload-config
mwww reload-style
mwww show
echo "mwww conf applied"


cp "$THEME_DIR/waybar/style.css" "$CONFIG_DIR/waybar/style.css"
killall waybar 2>/dev/null
waybar &
echo "waybar conf applied"


cp "$THEME_DIR/cava/config" "$CONFIG_DIR/cava/config"
kill -SIGUSR2 $(pgrep cava)
echo "cava conf applied"


cp "$THEME_DIR/wofi/style.css" "$CONFIG_DIR/wofi/style.css"
echo "wofi conf applied"


cp "$THEME_DIR/starship.toml" "$CONFIG_DIR/starship.toml"
echo "starship conf applied"


cp "$THEME_DIR/theme-picker/config.yaml" "$CONFIG_DIR/theme-picker/config.yaml"
echo "theme picker conf applied"


cp "$THEME_DIR/hypr/hyprlock/avatar" "$CONFIG_DIR/hypr/hyprlock/avatar"
cp "$THEME_DIR/hypr/hyprlock.conf" "$CONFIG_DIR/hypr/hyprlock.conf"
echo "hyprlock conf applied"
